import { test, assert, describe } from 'vitest'
import sharp from 'sharp'

// Note: We test sharp/EXIF functionality directly without importing lastfm.ts
// because lastfm.ts requires LAST_FM_API_KEY at module load time

describe('Last.fm Collage - Image Processing', () => {
  test('sharp can add EXIF metadata to JPEG', async () => {
    // Create a minimal valid JPEG using sharp
    const testImage = await sharp({
      create: {
        width: 100,
        height: 100,
        channels: 3,
        background: { r: 255, g: 0, b: 0 },
      },
    })
      .jpeg()
      .toBuffer()

    const altText = 'Test album by Test artist [10 scrobbles]'

    // Add EXIF metadata (same logic as addExifMetadata)
    const imageWithExif = await sharp(testImage)
      .withMetadata({
        exif: {
          IFD0: {
            ImageDescription: altText,
            Copyright: 'Generated by eligundry.com for testuser',
            Software: 'eligundry.com Last.fm Collage Generator',
          },
        },
      })
      .jpeg({ quality: 90 })
      .toBuffer()

    // Verify it's still a valid JPEG
    const signature = imageWithExif.slice(0, 2).toString('hex')
    assert.equal(signature, 'ffd8', 'Output should still be valid JPEG')

    // Read back the EXIF metadata using sharp
    const metadata = await sharp(imageWithExif).metadata()

    // Verify EXIF data was embedded
    assert.ok(metadata.exif, 'Image should have EXIF data')
  })

  test('JPEG buffer has valid magic bytes', async () => {
    // Create a test JPEG using sharp
    const testJpeg = await sharp({
      create: {
        width: 100,
        height: 100,
        channels: 3,
        background: { r: 0, g: 0, b: 255 },
      },
    })
      .jpeg()
      .toBuffer()

    // Check JPEG magic bytes (FFD8FF)
    const magicBytes = testJpeg.slice(0, 3).toString('hex')
    assert.equal(
      magicBytes,
      'ffd8ff',
      'Buffer should start with JPEG magic bytes'
    )
  })

  test('sharp preserves image dimensions through EXIF addition', async () => {
    const width = 900
    const height = 900

    // Create a test image at the expected collage size
    const testImage = await sharp({
      create: {
        width,
        height,
        channels: 3,
        background: { r: 128, g: 128, b: 128 },
      },
    })
      .jpeg()
      .toBuffer()

    const imageWithExif = await sharp(testImage)
      .withMetadata({
        exif: {
          IFD0: {
            ImageDescription: 'Test alt text',
          },
        },
      })
      .jpeg({ quality: 90 })
      .toBuffer()

    const metadata = await sharp(imageWithExif).metadata()

    assert.equal(metadata.width, width, 'Width should be preserved')
    assert.equal(metadata.height, height, 'Height should be preserved')
    assert.equal(metadata.format, 'jpeg', 'Format should be JPEG')
  })

  test('900x900 JPEG has reasonable file size', async () => {
    // A 900x900 JPEG with some noise should be reasonably sized
    // Solid colors compress very small, so we add noise
    const testImage = await sharp({
      create: {
        width: 900,
        height: 900,
        channels: 3,
        background: { r: 100, g: 100, b: 100 },
        noise: {
          type: 'gaussian',
          mean: 128,
          sigma: 30,
        },
      },
    })
      .jpeg({ quality: 90 })
      .toBuffer()

    // With noise, should be larger than 10KB
    // A real collage with album art will be much larger
    assert.ok(
      testImage.length > 1024,
      `Image should be at least 1KB, got ${testImage.length}`
    )
    assert.ok(
      testImage.length < 5 * 1024 * 1024,
      `Image should be less than 5MB, got ${testImage.length}`
    )
  })
})
