version: 2

updates:
  - package-ecosystem: npm
    directory: "/next"
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
  - package-ecosystem: gomod
    directory: "/api"
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
