FROM node:12 AS builder

# Install the node modules
WORKDIR /opt/modules
ADD ./gatsby/package.* /opt/modules/
RUN npm ci

# Build the application
WORKDIR /opt/gatsby
ADD ./gatsby /opt/gatsby
RUN ln -s /opt/modules/node_modules /opt/gatsby/node_modules
RUN gatsby build

# Copy the compiled application into a lightweight nginx container
FROM nginx:alpine AS final
ADD ./docker/frontend.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /opt/gatsby/public /usr/share/nginx/html
