version: '3'
services:
  api:
    container_name: eg-api
    image: eligundry/api.eligundry.com:latest
    entrypoint: /go/bin/watcher
    env_file:
      - ./.env
    build:
      context: ./
      dockerfile: Dockerfile.api
    environment:
      AUTH_USER: eligundry
      AUTH_PASSWORD: password
      CGO_CFLAGS: "-DSQLITE_ENABLE_JSON1"
    networks:
      backend: {}
    volumes:
      - ./api:/src
      - ./data:/opt/data

networks:
  backend:
    driver: bridge
