version: '2'
services:
  website:
    image: 'eligundry/eligundry.com'
    build: .
    container_name: 'eligundry.com'
    environment:
      - RUN_LEKTOR=true
    ports:
      - "5000:5000"
      - "8080:80"
    volumes:
      - .:/opt/eligundry.com
