version: '2'
services:
  website:
    image: eligundry/eligundry.com
    build: .
    container_name: website
    environment:
      - RUN_LEKTOR=${RUN_LEKTOR}
      - VIRTUAL_HOST=eligundry.localhost,eligundry.com
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=eligundry.com,www.eligundry.com
      - LETSENCRYPT_EMAIL=eligundry@gmail.com
      - LETSENCRYPT_TEST=${LETSENCRYPT_TEST}
    ports:
      - "5000:5000"
      - "8080:8080"
    volumes:
      - .:/opt/eligundry.com
      - ./docker/site.conf:/etc/nginx/sites-enabled/eligundry.com

  nginx:
    image: jwilder/nginx-proxy:alpine
    container_name: nginx
    environment:
      - ENABLE_IPV6=true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/conf.d
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - ./nginx/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    volumes:
      - ./nginx/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - nginx
