version: '3'
services:
  proxy: 
    container_name: eg-proxy
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    environment:
      DOMAINS: 'eligundry.dev -> http://docker-host:8000'
      STAGE: 'local'
    volumes:
      - data_https_portal:/var/lib/https-portal
      - ./docker/eligundry.dev.ssl.conf.erb:/var/lib/nginx-conf/eligundry.dev.ssl.conf.erb

  docker-host:
    container_name: eg-dh
    container_name: oms-docker-host
    image: qoomon/docker-host
    cap_add:
      - NET_ADMIN
      - NET_RAW

volumes:
  data_https_portal: {}
