[build]
  command = 'npm run build'
  publish = '.next'

[build.environment]
  NODE_VERSION = '16'

[[plugins]]
  package = '@netlify/plugin-nextjs'

[functions]
  included_files = ["!node_modules/canvas/**/*"]

[[headers]]
  for = "/_ipx/*"

  [headers.values]
    Cache-Control = '''
    public,
    s-max-age=365000000, 
    max-age=365000000, 
    immutable'''
