[build]
  command = 'npm run build'
  publish = '_site'

[build.environment]
  NODE_VERSION = '18'

[dev]
  command = 'npm start'

[[headers]]
  for = "/*.rss"

  [headers.values]
    Content-Type = "application/rss+xml; charset=UTF-8"
