[package]
name = "rust-api"
version = "0.1.0"
authors = ["Eli Gundry <eligundry@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.4"
