[build]
  command = 'npm run build'
  publish = 'dist'

[build.environment]
  NODE_VERSION = '18'

[[plugins]]
  package = 'netlify-plugin-cache'
  [plugins.inputs]
  paths = ['.cache', 'public/astro-fontaine']
