name: Docker Build & Push
on:
  push:
    branches:
      - master
      - gatsby-take-2

jobs:
  api:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: whoan/docker-build-with-cache-action@v3
      with:
        username: eligundry
        password: "${{ secrets.DOCKER_PASSWORD }}"
        image_name: eligundry/api.eligundry.com
        image_tag: latest
        dockerfile: Dockerfile.api

  frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: whoan/docker-build-with-cache-action@v3
      with:
        username: eligundry
        password: "${{ secrets.DOCKER_PASSWORD }}"
        image_name: eligundry/website.eligundry.com
        image_tag: latest
        dockerfile: Dockerfile.frontend
