name: Docker Build & Push
on:
  push:
    branches:
      - master
      - gatsby-learnings

  workflow_dispatch:
    inputs:
      clear_gatsby_cache:
        description: 'Should the Gatsby cache be cleared before building (true/false)?'
        required: false
        default: "false"

jobs:
  api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azure/docker-login@v1
        with:
          username: eligundry
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: satackey/action-docker-layer-caching@v0.0.8
        continue-on-error: true
      - name: Docker Build
        run: docker build -t eligundry/api.eligundry.com -f Dockerfile.api .
      - name: Docker Push
        run: docker push eligundry/api.eligundry.com

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install npm@7
        run: npm install -g npm@7

      - uses: bahmutov/npm-install@v1
        with:
          working-directory: gatsby

      # Incremental builds in Gatsby!
      # https://dev.to/danielbayerlein/incremental-gatsby-builds-with-github-actions-2p7o
      # - name: Cache Gatsby
      #   id: gatsby-cache-build
      #   uses: actions/cache@v2
      #   with:
      #     path: |
      #       gatsby/public
      #       gatsby/.cache
      #     key: ${{ runner.os }}-gatsby-build-${{ github.run_id }}
      #     restore-keys: |
      #       ${{ runner.os }}-gatsby-build-

      - name: Build and deploy site
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DO_SPACES_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DO_SPACES_SECRET }}
          DO_SPACES_ENDPOINT: "https://nyc3.digitaloceanspaces.com" 
          DO_SPACES_BUCKET: nyc-cdn.eligundry.com
        run: |
          npm --prefix=gatsby run build:gh-actions
          ./scripts/deploy-assets.sh

  deploy:
    runs-on: ubuntu-latest
    needs:
      - api
      - frontend
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install requests

      - name: Deploy to production
        env:
          SALT_PASSWORD: ${{ secrets.SALT_PASSWORD }}
        run: python scripts/deploy.py
