name: Docker Build & Push
on:
  push:
    branches:
      - master
      - gatsby-take-2

jobs:
  api:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: whoan/docker-build-with-cache-action@v3
      with:
        username: eligundry
        password: "${{ secrets.DOCKER_PASSWORD }}"
        image_name: eligundry/api.eligundry.com
        image_tag: latest
        dockerfile: Dockerfile.api

  frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: whoan/docker-build-with-cache-action@v3
      with:
        username: eligundry
        password: "${{ secrets.DOCKER_PASSWORD }}"
        image_name: eligundry/website.eligundry.com
        image_tag: latest
        dockerfile: Dockerfile.frontend

  deploy:
    runs-on: ubuntu-latest
    needs:
      - api
      - frontend
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install dependencies
      run: pip install requests

    - name: Deploy to production
      run: python scripts/deploy.py
