name: Docker Build & Push
on:
  push:
    branches:
      - master
    paths:
      - 'api/**'

jobs:
  api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azure/docker-login@v1
        with:
          username: eligundry
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: satackey/action-docker-layer-caching@v0.0.8
        continue-on-error: true
      - name: Docker Build
        run: docker build -t eligundry/api.eligundry.com -f Dockerfile.api .
      - name: Docker Push
        run: docker push eligundry/api.eligundry.com

  deploy:
    runs-on: ubuntu-latest
    needs:
      - api
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install requests

      - name: Deploy to production
        env:
          SALT_PASSWORD: ${{ secrets.SALT_PASSWORD }}
        run: python scripts/deploy.py
