name: Pull Request CI
on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          node-version-file: '.nvmrc'

      - name: Install Dependencies
        id: dependencies
        run: |
          pnpm --version
          pnpm install

      - name: Run linters
        if: steps.dependencies.conclusion == 'success' && !cancelled()
        run: pnpm run lint

      - name: Astro check
        if: steps.dependencies.conclusion == 'success' && !cancelled()
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: |
          ./node_modules/.bin/netlify env:list --plain > './.env'
          pnpm run astro-check
