name: Pull Request CI
on:
  pull_request:
    branches:
      - main
      - master

jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: bahmutov/npm-install@v1
        with:
          working-directory: gatsby
      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          eslint: true
          eslint_dir: gatsby

  type-check:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: bahmutov/npm-install@v1
        with:
          working-directory: gatsby
      - name: Check types
        run: npm run type-check
